/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

import LoginPage from "../../pages/swift/LoginPage";
import HomePage from "../../pages/swift/HomePage";
import AuthorizationPage from "../../pages/swift/AuthorizationPage";
import MX_029_Page from "../../pages/swift/MX_029_Page";
import MX_109_Page from "../../pages/swift/MX_109_Page";
import MX_Pacs_002_Page from "../../pages/swift/MX_Pacs_002_Page";
import MX_Pacs_004_Page from "../../pages/swift/MX_Pacs_004_Page";
import MX_Pacs_008_Page from "../../pages/swift/MX_Pacs_008_Page";
import MX_Pacs_009_Page from "../../pages/swift/MX_Pacs_009_Page";
import MX_Camt_105_Page from "../../pages/swift/MX_Camt_105_Page";
import MX_Camt_055_Page from "../../pages/swift/MX_Camt_055_Page";
import { verifyAlertMessage } from "../../utils/commonUtils";

describe("Automation Suite", () => {
  beforeEach("Login with valid credentials", () => {
    cy.clearCookies();
    cy.clearLocalStorage();

    cy.task("readExcel", {
      filePath: "cypress/fixtures/credentials.xlsx",
      sheetName: "login_credentials",
    }).then((data) => {
      const user = data[0];
      cy.log(`Logging in as: ${user.username}`);

      LoginPage.visit(user.url);
      cy.url({ timeout: 15000 }).should("include", "/realms"); // validation; this part can be skipped

      LoginPage.login(user.username, user.password);
      cy.url().should("include", "/landing"); // validation; this part can be skipped
    });
  });

  it("MX_029 Test", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath('3709')
    HomePage.search_MX_Message();
    HomePage.goToPage("CAMT.029.001.09 Resolution Of Investigation");
    MX_029_Page.charSetField();
    MX_029_Page.inputFromBIC();
    MX_029_Page.inputToBIC();
    MX_029_Page.fromClearingSystemID();
    MX_029_Page.toClearingSystemID();
    MX_029_Page.assignerClearingSystemID();
    MX_029_Page.assigneeClearingSystemID();
    MX_029_Page.fromMemberID();
    MX_029_Page.toMemberID();
    MX_029_Page.assignerMemberID();
    MX_029_Page.assigneeMemberID();
    MX_029_Page.fromLei();
    MX_029_Page.toLei();
    MX_029_Page.assignerLei();
    MX_029_Page.assigneeLei();
    MX_029_Page.copyDuplicateField();
    MX_029_Page.marketPracticeRegistryField();
    MX_029_Page.marketPracticeIdentificationField();
    MX_029_Page.relatedCharacterSetField();
    // MX_029_Page.relatedFromBIC();
    // MX_029_Page.relatedToBIC();
    MX_029_Page.businessMsg();
    MX_029_Page.relatedBusinessMsgID();
    MX_029_Page.assignmentIdentificationField();
    MX_029_Page.assignerBIC();
    MX_029_Page.confirmationDialog();
    MX_029_Page.cancellationStatusID();
    MX_029_Page.caseIdentificationField();
    MX_029_Page.creatorTypeField();
    MX_029_Page.agentBIC();
    MX_029_Page.originalMsgId();
    MX_029_Page.originalMsgNameId();
    MX_029_Page.UETR();
    MX_029_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("CAMT029");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_029_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("CAMT_109 Automation", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3722");
    HomePage.search_MX_Message();
    HomePage.goToPage("CAMT.109.001.01 Cheque Cancellation Or Stop Report");
    MX_109_Page.charSetField();
    MX_109_Page.inputFromBIC();
    MX_109_Page.inputToBIC();
    MX_109_Page.fromClearingSystemID();
    MX_109_Page.toClearingSystemID();
    MX_109_Page.fromMemberID();
    MX_109_Page.toMemberID();
    MX_109_Page.fromLei();
    MX_109_Page.toLei();
    MX_109_Page.businessMsg();
    MX_109_Page.msgID();
    MX_109_Page.dateCreationField();
    MX_109_Page.copyDuplicateField();
    MX_109_Page.priorityField();
    MX_109_Page.registryField();
    MX_109_Page.numberOfCheques();
    MX_109_Page.chequeIdentificationField();
    MX_109_Page.originalIdentification();
    MX_109_Page.chequeNumber();
    MX_109_Page.issueDateField();
    MX_109_Page.currencyField();
    MX_109_Page.amountField();
    MX_109_Page.chequeEffectiveDateField();
    MX_109_Page.chequeCancellationOriginatorField();
    MX_109_Page.codeField();
    MX_109_Page.chequeCancellationAdditionalInfoField();
    MX_109_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("CAMT109");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_109_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("PACS_002 Automation", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3723");
    HomePage.search_MX_Message();
    HomePage.goToPage("PACS.002.001.10 FI To FI Payment Status Report");
    MX_Pacs_002_Page.charSetField();
    MX_Pacs_002_Page.inputFromBIC();
    MX_Pacs_002_Page.inputToBIC();
    MX_Pacs_002_Page.fromClearingSystemID();
    MX_Pacs_002_Page.toClearingSystemID();
    MX_Pacs_002_Page.fromMemberID();
    MX_Pacs_002_Page.toMemberID();
    MX_Pacs_002_Page.fromLei();
    MX_Pacs_002_Page.toLei();
    // MX_Pacs_002_Page.priorityField();
    MX_Pacs_002_Page.businessMsgID();
    // MX_Pacs_002_Page.registryField();
    // MX_Pacs_002_Page.marketIdentificationField();
    MX_Pacs_002_Page.copyDuplicateField();
    MX_Pacs_002_Page.possibleDuplicateField();
    MX_Pacs_002_Page.relatedCharSetField();
    MX_Pacs_002_Page.relatedFromBIC();
    MX_Pacs_002_Page.relatedToBIC();
    MX_Pacs_002_Page.relatedFromClearingSystemID();
    MX_Pacs_002_Page.relatedToClearingSystemID();
    MX_Pacs_002_Page.relatedFromMemberID();
    MX_Pacs_002_Page.relatedToMemberID();
    MX_Pacs_002_Page.relatedFromLei();
    MX_Pacs_002_Page.relatedToLei();
    MX_Pacs_002_Page.businessMsg();
    MX_Pacs_002_Page.msgID();
    MX_Pacs_002_Page.businessServiceField();
    MX_Pacs_002_Page.dateCreationField();
    MX_Pacs_002_Page.originalMsgIdentification();
    MX_Pacs_002_Page.originalMsgNameIdentification();
    MX_Pacs_002_Page.originalEndToEndID();
    MX_Pacs_002_Page.transactionStatus();
    // MX_Pacs_002_Page.originatorNameField();
    // MX_Pacs_002_Page.originatorCountryField();
    // MX_Pacs_002_Page.originatorPostalDepartmentField();
    // MX_Pacs_002_Page.originatorPostalStreetField();
    // MX_Pacs_002_Page.originatorPostalPostCodeField();
    // MX_Pacs_002_Page.originatorPostalTownNameField();
    // MX_Pacs_002_Page.originatorPostalDistrictNameField();
    // MX_Pacs_002_Page.originatorPostalCountryNameField();
    // MX_Pacs_002_Page.reasonCodeField();
    // MX_Pacs_002_Page.reasonPropietaryField();
    // MX_Pacs_002_Page.clearingSystemRef();
    MX_Pacs_002_Page.instrucingAgentBicfi();
    MX_Pacs_002_Page.instrucingClearingMemberID();
    MX_Pacs_002_Page.instrucingClearingID();
    MX_Pacs_002_Page.instrucedAgentBicfi();
    MX_Pacs_002_Page.instrucedClearingMemberID();
    MX_Pacs_002_Page.instrucedClearingID();
    MX_Pacs_002_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("PACS002");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Pacs_002_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("PACS_004 Automation", () => {
    HomePage.menu1();
    HomePage.searchByFastPath("3725");
    HomePage.search_MX_Message();
    HomePage.goToPage("PACS.004.001.09 Payment Return");
    MX_Pacs_004_Page.charSetField();
    MX_Pacs_004_Page.inputFromBIC();
    MX_Pacs_004_Page.inputToBIC();
    MX_Pacs_004_Page.fromClearingSystemID();
    MX_Pacs_004_Page.toClearingSystemID();
    MX_Pacs_004_Page.fromMemberID();
    MX_Pacs_004_Page.toMemberID();
    MX_Pacs_004_Page.fromLei();
    MX_Pacs_004_Page.toLei();
    MX_Pacs_004_Page.businessMsgID();
    MX_Pacs_004_Page.groupHeaderMsgID();
    MX_Pacs_004_Page.groupHeaderDateCreationField();
    MX_Pacs_004_Page.originalInstructionIdentification();
    MX_Pacs_004_Page.originalEndToEndID();
    MX_Pacs_004_Page.internetBankingSettlementDate();
    MX_Pacs_004_Page.returnedInstrucedCurrencyField();
    MX_Pacs_004_Page.returnedInstrucedAmountField();
    MX_Pacs_004_Page.chargeBearerField();
    // MX_Pacs_004_Page.priorityField();
    // MX_Pacs_004_Page.registryField();
    // MX_Pacs_004_Page.marketIdentificationField();
    // MX_Pacs_004_Page.copyDuplicateField();
    // MX_Pacs_004_Page.possibleDuplicateField();
    // MX_Pacs_004_Page.relatedCharSetField();
    // MX_Pacs_004_Page.relatedFromBIC();
    // MX_Pacs_004_Page.relatedToBIC();
    // MX_Pacs_004_Page.relatedFromClearingSystemID();
    // MX_Pacs_004_Page.relatedToClearingSystemID();
    // MX_Pacs_004_Page.relatedFromMemberID();
    // MX_Pacs_004_Page.relatedToMemberID();
    // MX_Pacs_004_Page.relatedFromLei();
    // MX_Pacs_004_Page.relatedToLei();
    // MX_Pacs_004_Page.msgID();
    // MX_Pacs_004_Page.businessServiceField();
    // MX_Pacs_004_Page.dateCreationField();
    // MX_Pacs_004_Page.originalMsgIdentification();
    // MX_Pacs_004_Page.originalMsgNameIdentification();
    // MX_Pacs_004_Page.originalEndToEndID();
    // MX_Pacs_004_Page.transactionStatus();
    // MX_Pacs_004_Page.originatorNameField();
    // MX_Pacs_004_Page.originatorCountryField();
    // MX_Pacs_004_Page.originatorPostalDepartmentField();
    // MX_Pacs_004_Page.originatorPostalStreetField();
    // MX_Pacs_004_Page.originatorPostalPostCodeField();
    // MX_Pacs_004_Page.originatorPostalTownNameField();
    // MX_Pacs_004_Page.originatorPostalDistrictNameField();
    // MX_Pacs_004_Page.originatorPostalCountryNameField();
    MX_Pacs_004_Page.reasonCodeField();
    // MX_Pacs_004_Page.reasonPropietaryField();
    // MX_Pacs_004_Page.clearingSystemRef();
    // MX_Pacs_004_Page.instrucingAgentBicfi();
    // MX_Pacs_004_Page.instrucingClearingMemberID();
    // MX_Pacs_004_Page.instrucingClearingID();
    // MX_Pacs_004_Page.instrucedAgentBicfi();
    // MX_Pacs_004_Page.instrucedClearingMemberID();
    // MX_Pacs_004_Page.instrucedClearingID();
    MX_Pacs_004_Page.debatorPartyName();
    // MX_Pacs_004_Page.creatorPartyName();
    MX_Pacs_004_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("PACS004");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Pacs_004_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("PACS_009 Automation", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3727");
    HomePage.search_MX_Message();
    HomePage.goToPage("PACS.009.001.08 Financial Institution Credit Transfer");
    MX_Pacs_009_Page.charSetField();
    MX_Pacs_009_Page.inputFromBIC();
    MX_Pacs_009_Page.inputToBIC();
    MX_Pacs_009_Page.fromClearingSystemID();
    MX_Pacs_009_Page.toClearingSystemID();
    MX_Pacs_009_Page.fromMemberID();
    MX_Pacs_009_Page.toMemberID();
    MX_Pacs_009_Page.fromLei();
    MX_Pacs_009_Page.toLei();
    MX_Pacs_009_Page.businessMsgID();
    MX_Pacs_009_Page.groupHeaderMsgID();
    // MX_Pacs_008_Page.groupHeaderDateCreationField();
    // MX_Pacs_008_Page.originalInstructionIdentification();
    MX_Pacs_009_Page.paymentEndToEndID();
    MX_Pacs_009_Page.paymentTransactionID();
    MX_Pacs_009_Page.paymentClearingSystemRef();
    // MX_Pacs_008_Page.internetBankingSettlementDate();
    MX_Pacs_009_Page.internetBankingSettlementPriorityField();
    // MX_Pacs_008_Page.returnedInstrucedCurrencyField();
    // MX_Pacs_008_Page.returnedInstrucedAmountField();
    MX_Pacs_009_Page.interBankCurrencyField();
    MX_Pacs_009_Page.internetBankingAMountField();
    MX_Pacs_009_Page.priorityField();
    // MX_Pacs_008_Page.registryField();
    // MX_Pacs_008_Page.marketIdentificationField();
    MX_Pacs_009_Page.copyDuplicateField();
    MX_Pacs_009_Page.possibleDuplicateField();
    // MX_Pacs_009_Page.relatedCharSetField();
    // MX_Pacs_009_Page.relatedFromBIC();
    // MX_Pacs_009_Page.relatedToBIC();
    // MX_Pacs_009_Page.relatedFromClearingSystemID();
    // MX_Pacs_009_Page.relatedToClearingSystemID();
    // MX_Pacs_009_Page.relatedFromMemberID();
    // MX_Pacs_009_Page.relatedToMemberID();
    // MX_Pacs_009_Page.relatedFromLei();
    // MX_Pacs_009_Page.relatedToLei();
    // MX_Pacs_009_Page.msgID();
    // MX_Pacs_009_Page.businessServiceField();
    // MX_Pacs_009_Page.dateCreationField();
    // MX_Pacs_009_Page.originalMsgIdentification();
    // MX_Pacs_009_Page.originalMsgNameIdentification();
    // MX_Pacs_009_Page.originalEndToEndID();
    // MX_Pacs_009_Page.transactionStatus();
    // MX_Pacs_009_Page.originatorNameField();
    // MX_Pacs_009_Page.originatorCountryField();
    // MX_Pacs_009_Page.originatorPostalDepartmentField();
    // MX_Pacs_009_Page.originatorPostalStreetField();
    // MX_Pacs_009_Page.originatorPostalPostCodeField();
    // MX_Pacs_009_Page.originatorPostalTownNameField();
    // MX_Pacs_009_Page.originatorPostalDistrictNameField();
    // MX_Pacs_009_Page.originatorPostalCountryNameField();
    // MX_Pacs_009_Page.reasonCodeField();
    // MX_Pacs_009_Page.reasonPropietaryField();
    // MX_Pacs_009_Page.clearingSystemRef();
    // MX_Pacs_009_Page.instrucingAgentBicfi();
    // MX_Pacs_009_Page.instrucingClearingMemberID();
    // MX_Pacs_009_Page.instrucingClearingID();
    // MX_Pacs_009_Page.instrucedAgentBicfi();
    // MX_Pacs_009_Page.instrucedClearingMemberID();
    // MX_Pacs_009_Page.instrucedClearingID();
    MX_Pacs_009_Page.debtorBic();
    MX_Pacs_009_Page.creditorBic();
    MX_Pacs_009_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("PACS009");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Pacs_009_Page.groupHeaderMsgIDText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("PACS_008 Automation", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3726");
    HomePage.search_MX_Message();
    HomePage.goToPage("PACS.008.001.08 FI To FI Customer Credit Transfer");
    MX_Pacs_008_Page.charSetField();
    MX_Pacs_008_Page.inputFromBIC();
    MX_Pacs_008_Page.inputToBIC();
    MX_Pacs_008_Page.fromClearingSystemID();
    MX_Pacs_008_Page.toClearingSystemID();
    MX_Pacs_008_Page.fromMemberID();
    MX_Pacs_008_Page.toMemberID();
    MX_Pacs_008_Page.fromLei();
    MX_Pacs_008_Page.toLei();
    MX_Pacs_008_Page.businessMsgID();
    MX_Pacs_008_Page.groupHeaderMsgID();
    // MX_Pacs_008_Page.groupHeaderDateCreationField();
    // MX_Pacs_008_Page.originalInstructionIdentification();
    MX_Pacs_008_Page.paymentEndToEndID();
    // MX_Pacs_008_Page.paymentTransactionID();
    MX_Pacs_008_Page.paymentClearingSystemRef();
    // MX_Pacs_008_Page.internetBankingSettlementDate();
    MX_Pacs_008_Page.internetBankingSettlementPriorityField();
    // MX_Pacs_008_Page.returnedInstrucedCurrencyField();
    // MX_Pacs_008_Page.returnedInstrucedAmountField();
    MX_Pacs_008_Page.interBankCurrencyField();
    MX_Pacs_008_Page.internetBankingAMountField();
    MX_Pacs_008_Page.priorityField();
    MX_Pacs_008_Page.chargeBearerField();
    // MX_Pacs_008_Page.registryField();
    // MX_Pacs_008_Page.marketIdentificationField();
    // MX_Pacs_008_Page.copyDuplicateField();
    // MX_Pacs_008_Page.possibleDuplicateField();
    // MX_Pacs_008_Page.relatedCharSetField();
    // MX_Pacs_008_Page.relatedFromBIC();
    // MX_Pacs_008_Page.relatedToBIC();
    // MX_Pacs_008_Page.relatedFromClearingSystemID();
    // MX_Pacs_008_Page.relatedToClearingSystemID();
    // MX_Pacs_008_Page.relatedFromMemberID();
    // MX_Pacs_008_Page.relatedToMemberID();
    // MX_Pacs_008_Page.relatedFromLei();
    // MX_Pacs_008_Page.relatedToLei();
    // MX_Pacs_008_Page.msgID();
    // MX_Pacs_008_Page.businessServiceField();
    // MX_Pacs_008_Page.dateCreationField();
    // MX_Pacs_008_Page.originalMsgIdentification();
    // MX_Pacs_008_Page.originalMsgNameIdentification();
    // MX_Pacs_008_Page.originalEndToEndID();
    // MX_Pacs_008_Page.transactionStatus();
    // MX_Pacs_008_Page.originatorNameField();
    // MX_Pacs_008_Page.originatorCountryField();
    // MX_Pacs_008_Page.originatorPostalDepartmentField();
    // MX_Pacs_008_Page.originatorPostalStreetField();
    // MX_Pacs_008_Page.originatorPostalPostCodeField();
    // MX_Pacs_008_Page.originatorPostalTownNameField();
    // MX_Pacs_008_Page.originatorPostalDistrictNameField();
    // MX_Pacs_008_Page.originatorPostalCountryNameField();
    // MX_Pacs_008_Page.reasonCodeField();
    // MX_Pacs_008_Page.reasonPropietaryField();
    // MX_Pacs_008_Page.clearingSystemRef();
    // MX_Pacs_008_Page.instrucingAgentBicfi();
    // MX_Pacs_008_Page.instrucingClearingMemberID();
    // MX_Pacs_008_Page.instrucingClearingID();
    // MX_Pacs_008_Page.instrucedAgentBicfi();
    // MX_Pacs_008_Page.instrucedClearingMemberID();
    // MX_Pacs_008_Page.instrucedClearingID();
    MX_Pacs_008_Page.debatorName();
    MX_Pacs_008_Page.debatorCountryName();
    MX_Pacs_008_Page.debatorPostalAddressPanel();
    MX_Pacs_008_Page.debatorPostalAddressDepartmentName();
    MX_Pacs_008_Page.debatorPostalAddressStreetName();
    MX_Pacs_008_Page.debatorPostalAddressPostCode();
    MX_Pacs_008_Page.debatorPostalAddressTownName();
    MX_Pacs_008_Page.debatorPostalAddressCountryName();
    MX_Pacs_008_Page.debtorBic();
    MX_Pacs_008_Page.creaditorName();
    MX_Pacs_008_Page.creaditorPostalAddressPanel();
    MX_Pacs_008_Page.creaditorPostalAddressDepartmentName();
    MX_Pacs_008_Page.creaditorPostalAddressStreetName();
    MX_Pacs_008_Page.creaditorPostalAddressPostCode();
    MX_Pacs_008_Page.creaditorPostalAddressTownName();
    MX_Pacs_008_Page.creaditorPostalAddressCountryName();
    MX_Pacs_008_Page.creditorBic();
    // MX_Pacs_008_Page.remittanceStructureddPanelHandle();
    // MX_Pacs_008_Page.remittanceStructuredReferredDocTypeNumber();
    // MX_Pacs_008_Page.remittanceStructuredReferredLineTypeNumber();
    MX_Pacs_008_Page.safeRemittanceStructuredFlow();
    MX_Pacs_008_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("PACS008");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Pacs_008_Page.groupMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("CAMT_105 Automation for Single Charge", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3718");
    HomePage.search_MX_Message();
    HomePage.goToPage("CAMT.105.001.02 Charges Payment Notification");
    MX_Camt_105_Page.chooseMessageVariant("Single Charge");
    MX_Camt_105_Page.charSetField();
    MX_Camt_105_Page.inputFromBIC();
    MX_Camt_105_Page.inputToBIC();
    MX_Camt_105_Page.fromClearingSystemID();
    MX_Camt_105_Page.toClearingSystemID();
    MX_Camt_105_Page.fromMemberID();
    MX_Camt_105_Page.toMemberID();
    MX_Camt_105_Page.fromLei();
    MX_Camt_105_Page.toLei();
    MX_Camt_105_Page.businessMsg();
    MX_Camt_105_Page.marketRegistryField();
    MX_Camt_105_Page.marketIDField();
    MX_Camt_105_Page.marketDateCreationField();
    MX_Camt_105_Page.copyDuplicateField();
    MX_Camt_105_Page.possibleCopyDuplicateField();
    MX_Camt_105_Page.priorityField();
    MX_Camt_105_Page.relatedCharSetField();
    MX_Camt_105_Page.relatedInputFromBIC();
    MX_Camt_105_Page.relatedInputToBIC();
    MX_Camt_105_Page.relatedFromClearingSystemID();
    MX_Camt_105_Page.relatedToClearingSystemID();
    MX_Camt_105_Page.relatedFromMemberID();
    MX_Camt_105_Page.relatedToMemberID();
    MX_Camt_105_Page.relatedFromLei();
    MX_Camt_105_Page.relatedToLei();
    MX_Camt_105_Page.relatedBusinessMsgID();
    MX_Camt_105_Page.relatedMsgDefinitionID();
    MX_Camt_105_Page.relatedBusinessService();
    MX_Camt_105_Page.relatedMarketDateCreationField();
    MX_Camt_105_Page.relatedCopyDuplicateField();
    MX_Camt_105_Page.relatedPriorityField();
    MX_Camt_105_Page.groupMsgID();
    MX_Camt_105_Page.groupChargeCreationDate();
    MX_Camt_105_Page.chargeRequestorBIC();
    MX_Camt_105_Page.crgReqClrMbrCode();
    MX_Camt_105_Page.crgReqClrMbrID();
    MX_Camt_105_Page.crgReqClrLei();
    MX_Camt_105_Page.chargesIdentification();
    MX_Camt_105_Page.underlyingTrnsMsgID();
    MX_Camt_105_Page.underlyingTrnsMsgNameID();
    MX_Camt_105_Page.numberOfChequesBrkdwn();
    MX_Camt_105_Page.crgItem1Currency();
    MX_Camt_105_Page.totalChargesAmt();
    MX_Camt_105_Page.totalChargeCurrencyField();
    MX_Camt_105_Page.totalCrgDebitCreditIndicator();
    MX_Camt_105_Page.crgItem1Amt();
    MX_Camt_105_Page.crgItem1DebitCreditIndicator();
    MX_Camt_105_Page.crgItem1TypeCode();
    MX_Camt_105_Page.crgBrkdwnValueDate();
    // MX_Camt_105_Page.numberOfCheques();
    // MX_Camt_105_Page.chequeIdentificationField();
    // MX_Camt_105_Page.originalIdentification();
    // MX_Camt_105_Page.chequeNumber();
    // MX_Camt_105_Page.issueDateField();
    // MX_Camt_105_Page.currencyField();
    // MX_Camt_105_Page.amountField();
    // MX_Camt_105_Page.chequeEffectiveDateField();
    // MX_Camt_105_Page.chequeCancellationOriginatorField();
    // MX_Camt_105_Page.codeField();
    // MX_Camt_105_Page.chequeCancellationAdditionalInfoField();
    MX_Camt_105_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("CAMT105");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Camt_105_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it("CAMT_105 Automation for Multiple Charges", () => {
    HomePage.menu1();
    // HomePage.searchByFastPath("3718");
    HomePage.search_MX_Message();
    HomePage.goToPage("CAMT.105.001.02 Charges Payment Notification");
    MX_Camt_105_Page.chooseMessageVariant("Multiple Charges");
    MX_Camt_105_Page.charSetField();
    MX_Camt_105_Page.inputFromBIC();
    MX_Camt_105_Page.inputToBIC();
    MX_Camt_105_Page.fromClearingSystemID();
    MX_Camt_105_Page.toClearingSystemID();
    MX_Camt_105_Page.fromMemberID();
    MX_Camt_105_Page.toMemberID();
    MX_Camt_105_Page.fromLei();
    MX_Camt_105_Page.toLei();
    MX_Camt_105_Page.businessMsg();
    MX_Camt_105_Page.marketRegistryField();
    MX_Camt_105_Page.marketIDField();
    MX_Camt_105_Page.marketDateCreationField();
    MX_Camt_105_Page.copyDuplicateField();
    MX_Camt_105_Page.possibleCopyDuplicateField();
    MX_Camt_105_Page.priorityField();
    MX_Camt_105_Page.relatedCharSetField();
    MX_Camt_105_Page.relatedInputFromBIC();
    MX_Camt_105_Page.relatedInputToBIC();
    MX_Camt_105_Page.relatedFromClearingSystemID();
    MX_Camt_105_Page.relatedToClearingSystemID();
    MX_Camt_105_Page.relatedFromMemberID();
    MX_Camt_105_Page.relatedToMemberID();
    MX_Camt_105_Page.relatedFromLei();
    MX_Camt_105_Page.relatedToLei();
    MX_Camt_105_Page.relatedBusinessMsgID();
    MX_Camt_105_Page.relatedMsgDefinitionID();
    MX_Camt_105_Page.relatedBusinessService();
    MX_Camt_105_Page.relatedMarketDateCreationField();
    MX_Camt_105_Page.relatedCopyDuplicateField();
    MX_Camt_105_Page.relatedPriorityField();
    MX_Camt_105_Page.groupMsgID();
    MX_Camt_105_Page.groupChargeCreationDate();
    //Multiple Charges
    MX_Camt_105_Page.mulNumberOfChequesBrkdwn();
    MX_Camt_105_Page.mulTotalChargesAmt();
    MX_Camt_105_Page.mulTotalChargeCurrencyField();
    MX_Camt_105_Page.mulTotalCrgDebitCreditIndicator();
    MX_Camt_105_Page.mulChargesIdentification();
    MX_Camt_105_Page.mulRecordIdentification();
    MX_Camt_105_Page.mulChargeRequestorBIC();
    MX_Camt_105_Page.mulCrgReqClrMbrCode();
    MX_Camt_105_Page.mulCrgReqClrMbrID();
    MX_Camt_105_Page.mulCrgReqClrLei();
    MX_Camt_105_Page.mulNumberOfChequesBrkdwn1();
    MX_Camt_105_Page.mulTotalChargesAmt1();
    MX_Camt_105_Page.mulTotalChargeCurrencyField1();
    MX_Camt_105_Page.mulTotalCrgDebitCreditIndicator1();
    MX_Camt_105_Page.mulCrgItem1Amt();
    MX_Camt_105_Page.mulCrgItem1Currency();
    MX_Camt_105_Page.mulCrgItem1DebitCreditIndicator();
    MX_Camt_105_Page.mulCrgItem1TypeCode();
    MX_Camt_105_Page.mulCrgItem2Amt();
    MX_Camt_105_Page.mulCrgItem2Currency();
    MX_Camt_105_Page.mulCrgItem2DebitCreditIndicator();
    MX_Camt_105_Page.mulCrgItem2TypeCode();
    MX_Camt_105_Page.mulRecordIdentification2();
    MX_Camt_105_Page.mulChargeRequestorBIC2();
    MX_Camt_105_Page.mulCrgReqClrMbrCode2();
    MX_Camt_105_Page.mulCrgReqClrMbrID2();
    MX_Camt_105_Page.mulCrgReqClrLei2();
    MX_Camt_105_Page.mulNumberOfChequesBrkdwn2();
    MX_Camt_105_Page.mulTotalChargesAmt2();
    MX_Camt_105_Page.mulTotalChargeCurrencyField2();
    MX_Camt_105_Page.mulTotalCrgDebitCreditIndicator2();
    MX_Camt_105_Page.mulCrgItem3Amt();
    MX_Camt_105_Page.mulCrgItem3Currency();
    MX_Camt_105_Page.mulCrgItem3DebitCreditIndicator();
    MX_Camt_105_Page.mulCrgItem3TypeCode();
    MX_Camt_105_Page.mulCrgItem4Amt();
    MX_Camt_105_Page.mulCrgItem4Currency();
    MX_Camt_105_Page.mulCrgItem4DebitCreditIndicator();
    MX_Camt_105_Page.mulCrgItem4TypeCode();
    // MX_Camt_105_Page.mulCrgBrkdwnValueDate();
    // MX_Camt_105_Page.numberOfCheques();
    // MX_Camt_105_Page.chequeIdentificationField();
    // MX_Camt_105_Page.originalIdentification();
    // MX_Camt_105_Page.chequeNumber();
    // MX_Camt_105_Page.issueDateField();
    // MX_Camt_105_Page.currencyField();
    // MX_Camt_105_Page.amountField();
    // MX_Camt_105_Page.chequeEffectiveDateField();
    // MX_Camt_105_Page.chequeCancellationOriginatorField();
    // MX_Camt_105_Page.codeField();
    // MX_Camt_105_Page.chequeCancellationAdditionalInfoField();
    // MX_Camt_105_Page.save();
    MX_Camt_105_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("CAMT105");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Camt_105_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });

  it.only("CAMT_055 Automation", () => {
    HomePage.menu1();
    HomePage.searchByFastPath("3713");
    // HomePage.search_MX_Message();
    // HomePage.goToPage("CAMT.055.001.08 Customer Payment Cancellation Requ");
    MX_Camt_055_Page.charSetField();
    MX_Camt_055_Page.inputFromBIC();
    MX_Camt_055_Page.inputToBIC();
    MX_Camt_055_Page.fromClearingSystemID();
    MX_Camt_055_Page.toClearingSystemID();
    MX_Camt_055_Page.fromMemberID();
    MX_Camt_055_Page.toMemberID();
    MX_Camt_055_Page.fromLei();
    MX_Camt_055_Page.toLei();
    MX_Camt_055_Page.businessMsg();
    // MX_Camt_055_Page.priorityField();
    // MX_Camt_055_Page.registryField();
    // MX_Camt_055_Page.marketIdentificationField();
    MX_Camt_055_Page.copyDuplicateField();
    MX_Camt_055_Page.possibleDuplicateField();
    // MX_Camt_055_Page.relatedCharSetField();
    MX_Camt_055_Page.assignerBIC();
    MX_Camt_055_Page.assigneeBIC();
    MX_Camt_055_Page.assignerClearingSystemID();
    MX_Camt_055_Page.assigneeClearingSystemID();
    MX_Camt_055_Page.assignerMemberID();
    MX_Camt_055_Page.assigneeMemberID();
    MX_Camt_055_Page.assignerLei();
    MX_Camt_055_Page.assigneeLei();
    MX_Camt_055_Page.originalPaymentID();
    // MX_Camt_055_Page.businessServiceField();
    MX_Camt_055_Page.originalMsgIdentification();
    MX_Camt_055_Page.originalMsgNameIdentification();
    MX_Camt_055_Page.originalDateCreationField();
    MX_Camt_055_Page.transCancellationID();
    MX_Camt_055_Page.caseID();
    MX_Camt_055_Page.creatorType();
    MX_Camt_055_Page.partyNameField();
    MX_Camt_055_Page.partyCountryField();
    MX_Camt_055_Page.partyPostalAddressPanelClick();
    MX_Camt_055_Page.partyPostalDepartmentField();
    MX_Camt_055_Page.partyPostalStreetNameField();
    MX_Camt_055_Page.partyPostalPostCodeField();
    MX_Camt_055_Page.partyPostalTownNameField();
    MX_Camt_055_Page.partyPostalDistrictNameField();
    MX_Camt_055_Page.partyPostalCountryNameField();
    MX_Camt_055_Page.originalInstructionID();
    MX_Camt_055_Page.originalEndToEndID();
    MX_Camt_055_Page.originalUETR();
    MX_Camt_055_Page.originalCurrencyField();
    MX_Camt_055_Page.originalInstructedAmt();
    MX_Camt_055_Page.originalExecutionDate();
    // MX_Camt_055_Page.originalCollectionDate();
    MX_Camt_055_Page.cancellationReasonCodeField();
    // MX_Camt_055_Page.reasonPropietaryField();
    // MX_Camt_055_Page.clearingSystemRef();
    // MX_Camt_055_Page.instrucingAgentBicfi();
    // MX_Camt_055_Page.instrucingClearingMemberID();
    // MX_Camt_055_Page.instrucingClearingID();
    // MX_Camt_055_Page.instrucedAgentBicfi();
    // MX_Camt_055_Page.instrucedClearingMemberID();
    // MX_Camt_055_Page.instrucedClearingID();
    MX_Camt_055_Page.save();
    verifyAlertMessage("saved");
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("CAMT055");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(
      MX_Camt_055_Page.businessMsgText,
    );
    AuthorizationPage.confirmAuthorization();
  });
});
