/// <reference types="cypress" />
/// <reference types="cypress-xpath" />

import LoginPage from "../pages/LoginPage";
import HomePage from "../pages/HomePage";
import AuthorizationPage from "../pages/AuthorizationPage";
import MessagePage from "../pages/MessagePage";
import MX_029_Page from "../pages/MX_029_Page";
import MX_109_Page from "../pages/MX_109_Page";
import MX_Pacs_002_Page from "../pages/MX_Pacs_002_Page";
import MX_Pacs_004_Page from "../pages/MX_Pacs_004_Page";
import MX_Pacs_009_Page from "../pages/MX_Pacs_009_Page";
import { commonLocators } from "../support/locators/commonLocators";

describe("Automation Suite", () => {
  beforeEach("Login with valid credentials", () => {
    cy.task("readExcel", {
      filePath: "cypress/fixtures/credentials.xlsx",
      sheetName: "login_credentials",
    }).then((data) => {
      const user = data[0];
      cy.log(`Logging in as: ${user.username}`);

      LoginPage.visit();

      LoginPage.login(user.username, user.password);
    });
  });

  it("Check MX Messages", () => {
    // homePage.search("PACS02");

    HomePage.menu();
    // HomePage.search("CAMT53");
    HomePage.search_MX_Message();
    HomePage.errorLog();
    // MessagePage.inputFromBIC();
    // MessagePage.inputToBIC();
    // MessagePage.businessMsg();
    // MessagePage.firstIdentificationField();
    // MessagePage.assignerBIC();
    // MessagePage.confirmationDialog();
    // MessagePage.cancellationStatusID();
    // MessagePage.secondIdentificationField();
    // HomePage.logout();
  });

  it("Check MX Messages Again", () => {
    // homePage.search("PACS02");
    HomePage.reloadWindow();
    HomePage.menu();
    // HomePage.menu1();
    // HomePage.search("CAMT53");
    // HomePage.search_MX_Message();
    HomePage.search_MX_Message1();
    HomePage.debug();
    HomePage.errorLog();
    // MessagePage.inputFromBIC();
    // MessagePage.inputToBIC();
    // MessagePage.businessMsg();
    // MessagePage.firstIdentificationField();
    // MessagePage.assignerBIC();
    // MessagePage.confirmationDialog();
    // MessagePage.cancellationStatusID();
    // MessagePage.secondIdentificationField();
    // HomePage.logout()
  });

  it("MX_029 Test", () => {
    HomePage.menu1();
    HomePage.search_MX_Message();
    HomePage.goToCamt_029();
    MX_029_Page.charSetField();
    MX_029_Page.inputFromBIC();
    MX_029_Page.inputToBIC();
    MX_029_Page.fromClearingSystemID();
    MX_029_Page.toClearingSystemID();
    MX_029_Page.assignerClearingSystemID();
    MX_029_Page.assigneeClearingSystemID();
    MX_029_Page.fromMemberID();
    MX_029_Page.toMemberID();
    MX_029_Page.assignerMemberID();
    MX_029_Page.assigneeMemberID();
    MX_029_Page.fromLei();
    MX_029_Page.toLei();
    MX_029_Page.assignerLei();
    MX_029_Page.assigneeLei();
    MX_029_Page.copyDuplicateField();
    MX_029_Page.marketPracticeRegistryField();
    MX_029_Page.marketPracticeIdentificationField();
    MX_029_Page.relatedCharacterSetField();
    // MX_029_Page.relatedFromBIC();
    // MX_029_Page.relatedToBIC();
    MX_029_Page.businessMsg();
    MX_029_Page.relatedBusinessMsgID();
    MX_029_Page.assignmentIdentificationField();
    MX_029_Page.assignerBIC();
    MX_029_Page.confirmationDialog();
    MX_029_Page.cancellationStatusID();
    MX_029_Page.caseIdentificationField();
    MX_029_Page.creatorTypeField();
    MX_029_Page.agentBIC();
    MX_029_Page.originalMsgId();
    MX_029_Page.originalMsgNameId();
    MX_029_Page.UETR();
    MX_029_Page.save();
  });

  it("CAMT_109 Automation", () => {
    HomePage.menu1();
    // HomePage.search("CAMT53");
    HomePage.search_MX_Message();
    HomePage.goToCamt_109();
    MX_109_Page.charSetField();
    MX_109_Page.inputFromBIC();
    MX_109_Page.inputToBIC();
    MX_109_Page.fromClearingSystemID();
    MX_109_Page.toClearingSystemID();
    MX_109_Page.fromMemberID();
    MX_109_Page.toMemberID();
    MX_109_Page.fromLei();
    MX_109_Page.toLei();
    MX_109_Page.businessMsg();
    MX_109_Page.msgID();
    MX_109_Page.dateCreationField();
    MX_109_Page.copyDuplicateField();
    MX_109_Page.priorityField();
    MX_109_Page.registryField();
    MX_109_Page.numberOfCheques();
    MX_109_Page.chequeIdentificationField();
    MX_109_Page.originalIdentification();
    MX_109_Page.chequeNumber();
    MX_109_Page.issueDateField();
    MX_109_Page.currencyField();
    MX_109_Page.amountField();
    MX_109_Page.chequeEffectiveDateField();
    MX_109_Page.chequeCancellationOriginatorField();
    MX_109_Page.codeField();
    MX_109_Page.chequeCancellationAdditionalInfoField();
    MX_109_Page.save();
  });

  it("PACS_002 Automation", () => {
    HomePage.menu1();
    // HomePage.search("CAMT53");
    HomePage.search_MX_Message();
    HomePage.goToPacs_002();
    MX_Pacs_002_Page.charSetField();
    MX_Pacs_002_Page.inputFromBIC();
    MX_Pacs_002_Page.inputToBIC();
    MX_Pacs_002_Page.fromClearingSystemID();
    MX_Pacs_002_Page.toClearingSystemID();
    MX_Pacs_002_Page.fromMemberID();
    MX_Pacs_002_Page.toMemberID();
    MX_Pacs_002_Page.fromLei();
    MX_Pacs_002_Page.toLei();
    MX_Pacs_002_Page.priorityField();
    MX_Pacs_002_Page.registryField();
    MX_Pacs_002_Page.marketIdentificationField();
    MX_Pacs_002_Page.copyDuplicateField();
    MX_Pacs_002_Page.possibleDuplicateField();
    MX_Pacs_002_Page.relatedCharSetField();
    MX_Pacs_002_Page.relatedFromBIC();
    MX_Pacs_002_Page.relatedToBIC();
    MX_Pacs_002_Page.relatedFromClearingSystemID();
    MX_Pacs_002_Page.relatedToClearingSystemID();
    MX_Pacs_002_Page.relatedFromMemberID();
    MX_Pacs_002_Page.relatedToMemberID();
    MX_Pacs_002_Page.relatedFromLei();
    MX_Pacs_002_Page.relatedToLei();
    MX_Pacs_002_Page.businessMsg();
    MX_Pacs_002_Page.msgID();
    MX_Pacs_002_Page.businessServiceField();
    MX_Pacs_002_Page.dateCreationField();
    MX_Pacs_002_Page.originalMsgIdentification();
    MX_Pacs_002_Page.originalMsgNameIdentification();
    MX_Pacs_002_Page.originalEndToEndID();
    MX_Pacs_002_Page.transactionStatus();
    MX_Pacs_002_Page.originatorNameField();
    MX_Pacs_002_Page.originatorCountryField();
    MX_Pacs_002_Page.originatorPostalDepartmentField();
    MX_Pacs_002_Page.originatorPostalStreetField();
    MX_Pacs_002_Page.originatorPostalPostCodeField();
    MX_Pacs_002_Page.originatorPostalTownNameField();
    MX_Pacs_002_Page.originatorPostalDistrictNameField();
    MX_Pacs_002_Page.originatorPostalCountryNameField();
    MX_Pacs_002_Page.reasonCodeField();
    MX_Pacs_002_Page.reasonPropietaryField();
    MX_Pacs_002_Page.clearingSystemRef();
    MX_Pacs_002_Page.instrucingAgentBicfi();
    MX_Pacs_002_Page.instrucingClearingMemberID();
    MX_Pacs_002_Page.instrucingClearingID();
    MX_Pacs_002_Page.instrucedAgentBicfi();
    MX_Pacs_002_Page.instrucedClearingMemberID();
    MX_Pacs_002_Page.instrucedClearingID();
    MX_Pacs_002_Page.save();
  });

  it("PACS_004 Automation", () => {
    HomePage.menu1();
    // HomePage.search("CAMT53");
    HomePage.search_MX_Message();
    HomePage.goToPacs_004();
    MX_Pacs_004_Page.charSetField();
    MX_Pacs_004_Page.inputFromBIC();
    MX_Pacs_004_Page.inputToBIC();
    MX_Pacs_004_Page.fromClearingSystemID();
    MX_Pacs_004_Page.toClearingSystemID();
    MX_Pacs_004_Page.fromMemberID();
    MX_Pacs_004_Page.toMemberID();
    MX_Pacs_004_Page.fromLei();
    MX_Pacs_004_Page.toLei();
    MX_Pacs_004_Page.businessMsgID();
    MX_Pacs_004_Page.groupHeaderMsgID();
    MX_Pacs_004_Page.groupHeaderDateCreationField();
    MX_Pacs_004_Page.originalInstructionIdentification();
    MX_Pacs_004_Page.originalEndToEndID();
    MX_Pacs_004_Page.internetBankingSettlementDate();
    MX_Pacs_004_Page.returnedInstrucedCurrencyField();
    MX_Pacs_004_Page.returnedInstrucedAmountField();
    MX_Pacs_004_Page.chargeBearerField();
    // MX_Pacs_004_Page.priorityField();
    // MX_Pacs_004_Page.registryField();
    // MX_Pacs_004_Page.marketIdentificationField();
    // MX_Pacs_004_Page.copyDuplicateField();
    // MX_Pacs_004_Page.possibleDuplicateField();
    // MX_Pacs_004_Page.relatedCharSetField();
    // MX_Pacs_004_Page.relatedFromBIC();
    // MX_Pacs_004_Page.relatedToBIC();
    // MX_Pacs_004_Page.relatedFromClearingSystemID();
    // MX_Pacs_004_Page.relatedToClearingSystemID();
    // MX_Pacs_004_Page.relatedFromMemberID();
    // MX_Pacs_004_Page.relatedToMemberID();
    // MX_Pacs_004_Page.relatedFromLei();
    // MX_Pacs_004_Page.relatedToLei();
    // MX_Pacs_004_Page.msgID();
    // MX_Pacs_004_Page.businessServiceField();
    // MX_Pacs_004_Page.dateCreationField();
    // MX_Pacs_004_Page.originalMsgIdentification();
    // MX_Pacs_004_Page.originalMsgNameIdentification();
    // MX_Pacs_004_Page.originalEndToEndID();
    // MX_Pacs_004_Page.transactionStatus();
    // MX_Pacs_004_Page.originatorNameField();
    // MX_Pacs_004_Page.originatorCountryField();
    // MX_Pacs_004_Page.originatorPostalDepartmentField();
    // MX_Pacs_004_Page.originatorPostalStreetField();
    // MX_Pacs_004_Page.originatorPostalPostCodeField();
    // MX_Pacs_004_Page.originatorPostalTownNameField();
    // MX_Pacs_004_Page.originatorPostalDistrictNameField();
    // MX_Pacs_004_Page.originatorPostalCountryNameField();
    MX_Pacs_004_Page.reasonCodeField();
    // MX_Pacs_004_Page.reasonPropietaryField();
    // MX_Pacs_004_Page.clearingSystemRef();
    MX_Pacs_004_Page.instrucingAgentBicfi();
    // MX_Pacs_004_Page.instrucingClearingMemberID();
    // MX_Pacs_004_Page.instrucingClearingID();
    MX_Pacs_004_Page.instrucedAgentBicfi();
    // MX_Pacs_004_Page.instrucedClearingMemberID();
    // MX_Pacs_004_Page.instrucedClearingID();
    MX_Pacs_004_Page.save();
  });

  it.only("PACS_009 Automation", () => {
    HomePage.menu1();
    // HomePage.search("CAMT53");
    HomePage.search_MX_Message();
    HomePage.goToPacs_009();
    MX_Pacs_009_Page.charSetField();
    MX_Pacs_009_Page.inputFromBIC();
    MX_Pacs_009_Page.inputToBIC();
    MX_Pacs_009_Page.fromClearingSystemID();
    MX_Pacs_009_Page.toClearingSystemID();
    MX_Pacs_009_Page.fromMemberID();
    MX_Pacs_009_Page.toMemberID();
    MX_Pacs_009_Page.fromLei();
    MX_Pacs_009_Page.toLei();
    MX_Pacs_009_Page.businessMsgID();
    MX_Pacs_009_Page.groupHeaderMsgID();
    // MX_Pacs_009_Page.groupHeaderDateCreationField();
    // MX_Pacs_009_Page.originalInstructionIdentification();
    MX_Pacs_009_Page.paymentEndToEndID();
    MX_Pacs_009_Page.paymentTransactionID();
    MX_Pacs_009_Page.paymentClearingSystemRef();
    // MX_Pacs_009_Page.internetBankingSettlementDate();
    MX_Pacs_009_Page.internetBankingSettlementPriorityField();
    // MX_Pacs_009_Page.returnedInstrucedCurrencyField();
    // MX_Pacs_009_Page.returnedInstrucedAmountField();
    MX_Pacs_009_Page.interBankCurrencyField();
    MX_Pacs_009_Page.internetBankingAMountField();
    MX_Pacs_009_Page.priorityField();
    // MX_Pacs_009_Page.registryField();
    // MX_Pacs_009_Page.marketIdentificationField();
    MX_Pacs_009_Page.copyDuplicateField();
    MX_Pacs_009_Page.possibleDuplicateField();
    // MX_Pacs_009_Page.relatedCharSetField();
    // MX_Pacs_009_Page.relatedFromBIC();
    // MX_Pacs_009_Page.relatedToBIC();
    // MX_Pacs_009_Page.relatedFromClearingSystemID();
    // MX_Pacs_009_Page.relatedToClearingSystemID();
    // MX_Pacs_009_Page.relatedFromMemberID();
    // MX_Pacs_009_Page.relatedToMemberID();
    // MX_Pacs_009_Page.relatedFromLei();
    // MX_Pacs_009_Page.relatedToLei();
    // MX_Pacs_009_Page.msgID();
    // MX_Pacs_009_Page.businessServiceField();
    // MX_Pacs_009_Page.dateCreationField();
    // MX_Pacs_009_Page.originalMsgIdentification();
    // MX_Pacs_009_Page.originalMsgNameIdentification();
    // MX_Pacs_009_Page.originalEndToEndID();
    // MX_Pacs_009_Page.transactionStatus();
    // MX_Pacs_009_Page.originatorNameField();
    // MX_Pacs_009_Page.originatorCountryField();
    // MX_Pacs_009_Page.originatorPostalDepartmentField();
    // MX_Pacs_009_Page.originatorPostalStreetField();
    // MX_Pacs_009_Page.originatorPostalPostCodeField();
    // MX_Pacs_009_Page.originatorPostalTownNameField();
    // MX_Pacs_009_Page.originatorPostalDistrictNameField();
    // MX_Pacs_009_Page.originatorPostalCountryNameField();
    // MX_Pacs_009_Page.reasonCodeField();
    // MX_Pacs_009_Page.reasonPropietaryField();
    // MX_Pacs_009_Page.clearingSystemRef();
    // MX_Pacs_009_Page.instrucingAgentBicfi();
    // MX_Pacs_009_Page.instrucingClearingMemberID();
    // MX_Pacs_009_Page.instrucingClearingID();
    // MX_Pacs_009_Page.instrucedAgentBicfi();
    // MX_Pacs_009_Page.instrucedClearingMemberID();
    // MX_Pacs_009_Page.instrucedClearingID();
    MX_Pacs_009_Page.debtorBic();
    MX_Pacs_009_Page.creditorBic();
    MX_Pacs_009_Page.save();
    AuthorizationPage.openMenuAndGoToAuthorization();
    AuthorizationPage.messageType("PACS009");
    AuthorizationPage.authorizeByBusinessMsgIdentifier(MX_Pacs_009_Page.businessMsg);
    AuthorizationPage.confirmAuthorization();
  });
});
